// Generated by CoffeeScript 1.3.3
var app, assets, express, google, port, stylus, _;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

_ = require('underscore');

google = require('google');

app = express();

app.use(assets());

app.set('view engine', 'jade');

app.get('/', function(req, resp) {
  return google("node.js best practices", function(err, next, links) {
    var results;
    results = _.map(links, function(link) {
      return link.title;
    });
    return resp.render('index', {
      results: results
    });
  });
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
